package.json, src/App.vue, src/components/Header.vue, src/components/HelloWorld.vue, src/main.js, src/pages/AssetDetail.vue, src/pages/AssetPlan.vue, src/pages/Login.vue, src/pages/MainPage.vue, src/pages/MyPage.vue, src/pages/Products.vue, src/router/temp.js, tailwind.config.js, yarn.lock
- ### feature/header-nav 
<br>
<br>
<br>
css 적용 한거 확인해주세요!
<br>
close #
=> [FEAT] header navigation 기능 구현 

package.json, src/App.vue, src/components/Header.vue, src/main.js, src/pages/Products.vue, src/stores/headerStore.js, yarn.lock
swiper 적용된 페이지에 스크롤 감지 안 돼서 생긴 오류
resolves: #18
#18 헤더 적용 오류
맞춤 상품 페이지에서 스크롤에 따른 헤더 활성화가 안되는 오류 수정
=> fix : 맞춤 상품 페이지 헤더 비활성화 오류 수정

src/App.vue, src/components/Header.vue, src/pages/Products.vue, src/stores/headerStore.js
#18 헤더 적용 오류
> 스크롤을 통한 활성화
> 호버를 통한 활성화
=> fix: 헤더 활성화 오류 수정

src/components/Login/SignCondition.vue, src/pages/Login.vue, src/pages/Signup.vue
> ex) #27 
약관 동의 버튼 클릭할때만 -> 화면 스크롤 가능 하게 수정
=> fix: 스크롤 이벤트 수정

src/pages/Products.vue, tailwind.config.js
#31
swiper를 이용해서 네비게이션 기능 구현
>
=> #31 feature/recommend navigation

src/components/MainPage/MainPageButton.vue, src/pages/AssetDetail.vue, tailwind.config.js
=> pr #35 to dev feat: 자산 분석 페이지 구현

src/App.vue, src/components/common/RecommendLoading.vue
=> #37 feature/recommend loading

src/components/AssetAnalyze/TotalCircle.vue, src/components/AssetAnalyze/TotalText.vue, src/css/tailwind.css, src/pages/AssetAnalyze.vue, tailwind.config.js
#53 
✔️ 노란색 배경 제거 
✔️  마진 조절 
✔️  글자색 일단 변경
>
=> style: 스타일 추가 후 merge

src/components/AllProducts/ProductItem.vue, src/components/common/CommonButton.vue, src/main.js, src/pages/AllProducts.vue, src/pages/Products.vue, src/router/router.js
=> #56 feature/all products view

src/components/AssetAnalyze/AnalyzeSavings.vue
=> style:배경 원 추가

src/components/AssetPlan/StrategyForPrivate.vue, src/components/AssetPlan/StrategyForPrivate/StrategyCircle.vue, src/components/AssetPlan/StrategyForPrivate/StrategyDept.vue, src/components/AssetPlan/StrategyForPrivate/StrategyDeptSolution.vue, src/components/AssetPlan/StrategyForPrivate/StrategyRecommend.vue, src/components/AssetPlan/StrategyForPrivate/StrategyText.vue, src/css/tailwind.css, tailwind.config.js
#61
자산 설계 페이지 개인 맞춤 전략 ui 구현
여러모로 어렵고 어지러운 작업이었다,,
문제도 좀 있는 거 같다,,
>
=> #61 feature/strategy for private 

src/components/AssetPlan/AssetPlanNavigation.vue, src/router/router.js
=> chore: router 정리

package.json, src/components/AssetAnalyze/AnalyzeButton.vue, src/components/AssetAnalyze/AnalyzeRange.vue, src/pages/AssetAnalyze.vue, tailwind.config.js, yarn.lock
#65 
🤔 자산 설계 페이지로 이동하는 버튼은 수정 예정!
>
=> #65 feature/analyze income range

src/components/Header.vue, src/components/Login/SignCondition.vue, src/components/MyPage/EditPassword.vue, src/components/MyPage/EditProfile.vue, src/components/MyPage/SideBar.vue, src/components/MyPage/WithdrawMember.vue, src/pages/AllProducts.vue, src/pages/AssetAnalyze.vue, src/pages/AssetDetail.vue, src/pages/AssetPlan.vue, src/pages/Login.vue, src/pages/MyPage.vue
=> #71 fix/modifying bgcolor

src/components/Login/SignSuccess.vue, src/components/MainPage/MainPageFirst.vue, src/pages/AssetAnalyze.vue, src/pages/AssetPlan.vue, src/pages/MyPage.vue, src/pages/Products.vue
=> style: 일부 페이지 수정

src/components/MyPage/EditPassword.vue, src/components/MyPage/EditProfile.vue, src/components/MyPage/WithdrawMember.vue, src/pages/MyPage.vue
=> chore: 배경 수정

src/components/MainPage/MainPageNavigation.vue, src/pages/MyPage.vue
=> chore: 간단 스타일 수정

src/apis/api/survey.js, src/components/Header.vue, src/components/MainPage/MainPageButton.vue, src/pages/Survey.vue, src/router/router.js
#83 
설문 결과 배열에 담아서 서버에 전송
아직 백과 연동 안돼서 확인은 불가
=> feat: 설문 결과 값 배열에 담아서 보내기

src/apis/api/user.js, src/components/Loading/AnalyzeLoading.vue, src/pages/Login.vue
로그인 여부에 따른 페이지 처리 해야 함,,
Resolves: #90
#90 
>
=> feat: 로그인 api 연동

src/components/Login/AuthenticationBtn.vue, src/pages/Signup.vue
=> #84 feature/link signup api

src/pages/Login.vue, src/pages/MyPage.vue, src/router/router.js, src/stores/auth.js
#93 
분석/설계/마이페이지 로그인 되었을 때만 접근할 수 있게 설정
로그인 후 가려고 했던 페이지로 리다이렉트
로그아웃 기능 구현
=> feat: 로그인, 로그아웃 기능 연동

src/App.vue, src/apis/api/assetAnalyze.js, src/components/Loading/AnalyzeLoading.vue, src/pages/AssetAnalyze.vue, src/stores/loadingStateStore.js
#104 
자산 분석 데이터 받아오는 동안 로딩페이지 보이게 구현
>
=> #104 feature/asset analyze is loading

src/components/AssetAnalyze/AnalyzeDebt.vue, src/components/AssetAnalyze/AnalyzeRange.vue, src/components/AssetAnalyze/AnalyzeSavings.vue, src/components/AssetAnalyze/TotalText.vue, src/components/AssetAnalyze/graph/DebtGraph.vue, src/components/AssetAnalyze/graph/IncomeGraph.vue, src/components/AssetAnalyze/graph/SavingsGraph.vue, src/components/AssetPlanStrategy/StrategyForPrivate.vue, src/components/MainPage/MainPageButton.vue, src/components/Products/CategoryButton.vue, src/components/Products/ProductsAllView/ProductsCards.vue, src/components/Products/Top3Products.vue, src/constant/productCategoryData.js, src/pages/AssetAnalyze.vue, src/pages/AssetDetail.vue, src/pages/Products.vue, src/pages/Survey.vue
#102 
맞춤 상품 및 자산 분석 페이지 디자인 수정 중간 PR
=> #102 fix/modify design

src/App.vue, src/components/AssetAnalyze/AnalyzeDebt.vue, src/components/AssetAnalyze/AnalyzeRange.vue, src/components/AssetAnalyze/graph/SavingsGraph.vue, src/components/Loading/AnalyzeLoading.vue, src/pages/AssetAnalyze.vue
=> fix :오류 수정

src/App.vue, src/components/AssetAnalyze/AnalyzeDebt.vue, src/components/AssetAnalyze/AnalyzeRange.vue, src/components/AssetAnalyze/AnalyzeSavings.vue, src/components/AssetAnalyze/TotalText.vue, src/components/Loading/AnalyzeLoading.vue, src/pages/AssetAnalyze.vue, src/stores/loadingStateStore.js
=> fix: 로딩 에러 해결

src/components/AssetAnalyze/AnalyzeDebt.vue, src/components/AssetAnalyze/AnalyzeRange.vue, src/components/AssetAnalyze/AnalyzeSavings.vue, src/components/AssetAnalyze/graph/SavingsGraph.vue, src/components/Header.vue, src/pages/MainPage.vue
=> #97 feature/analyze api

src/components/AssetAnalyze/AnalyzeRange.vue, src/components/AssetAnalyze/TotalCircle.vue, src/components/Header.vue, src/components/MainPage/MainPageNavigation.vue, src/pages/Login.vue, src/pages/MyPage.vue, src/pages/Signup.vue, src/stores/auth.js
=> #113 feature localstorage

src/components/Header.vue, src/components/Login/AuthenticationBtn.vue, src/components/MyPage/EditProfile.vue, src/stores/profileStore.js
=> #118 fix/mypage

src/apis/api/assetAnalyze.js, src/apis/api/favorites.js, src/components/AllProducts/ProductItem.vue, src/components/MyPage/LikeProducts.vue, src/components/Products/ProductsAllView/ProductsCards.vue, src/pages/AllProducts.vue, src/pages/AssetAnalyze.vue, src/pages/AssetPlanSimulation.vue, src/pages/MyPage.vue
=> #107 feature/favorites api connect

src/components/AssetAnalyze/AnalyzeRange.vue, src/components/AssetAnalyze/TotalCircle.vue, src/components/MyPage/EditPassword.vue
=> feat: 페이지 오류 찾기

src/components/MyPage/LikeProducts.vue, src/pages/MyPage.vue
=> feat: 마이페이지 찜한 상품 조회
